/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import alertaj.Jop;
import controle.ControleCliente;
import controle.ControleEndereco;
import controle.ControleTipoEndereco;
import controle.ControleTipoPessoa;
import controle.ControleUf;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Endereco;
import modelo.TipoEndereco;
import modelo.TipoPessoa;
import modelo.Uf;

/**
 *
 * @author T-Gamer
 */
public class VisaoCliente extends javax.swing.JFrame {

    private List<TipoPessoa> tipoPessoas;
    private List<TipoEndereco> tipoEnderecos;
    private List<Uf> ufs;
    private List<Cliente> clientes;

    /**
     * Creates new form PaisVisao
     */
    public VisaoCliente() {

        initComponents();
        carregarListaUfs();
        carregarListaTipoEnderecos();
        carregarListaTipoPessoas();
        carregarListaClientes();
        desativarBotoes();
        desativarCamposDeTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jplOpcoes = new javax.swing.JPanel();
        jbtIncluir = new javax.swing.JButton();
        jbtNovo = new javax.swing.JToggleButton();
        jbtSalvar = new javax.swing.JToggleButton();
        jbtExcluir = new javax.swing.JToggleButton();
        jbtAlterar = new javax.swing.JToggleButton();
        jbtCancelar = new javax.swing.JToggleButton();
        jbtConsulta = new javax.swing.JButton();
        jbtSair = new javax.swing.JToggleButton();
        jbtBuscaCodigo = new javax.swing.JButton();
        jplCampos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfLogradouro = new javax.swing.JTextField();
        jtfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbTipoPessoa = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jtfSobrenome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfRg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfOrgaoExpedidor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcbTipoEndereco = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jcbEstados = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jtfCidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtfCep = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfComplemento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfReferencia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsulta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jplTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Manter Cliente");

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_pequeno.png"))); // NOI18N

        javax.swing.GroupLayout jplTituloLayout = new javax.swing.GroupLayout(jplTitulo);
        jplTitulo.setLayout(jplTituloLayout);
        jplTituloLayout.setHorizontalGroup(
            jplTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplTituloLayout.createSequentialGroup()
                .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jplTituloLayout.setVerticalGroup(
            jplTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplTituloLayout.createSequentialGroup()
                .addGroup(jplTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlLogo)
                    .addGroup(jplTituloLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jplOpcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtIncluir.setText("Incluir");
        jbtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIncluirActionPerformed(evt);
            }
        });

        jbtNovo.setText("Novo");
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtExcluir.setText("Excluir");
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtAlterar.setText("Alterar");
        jbtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarActionPerformed(evt);
            }
        });

        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jbtConsulta.setText("Consultar");
        jbtConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConsultaActionPerformed(evt);
            }
        });

        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });

        jbtBuscaCodigo.setText("Busca por Código");
        jbtBuscaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscaCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplOpcoesLayout = new javax.swing.GroupLayout(jplOpcoes);
        jplOpcoes.setLayout(jplOpcoesLayout);
        jplOpcoesLayout.setHorizontalGroup(
            jplOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jplOpcoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jplOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplOpcoesLayout.createSequentialGroup()
                        .addGroup(jplOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jbtBuscaCodigo)
                            .addComponent(jbtIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplOpcoesLayout.createSequentialGroup()
                        .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        jplOpcoesLayout.setVerticalGroup(
            jplOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtBuscaCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtSair)
                .addGap(31, 31, 31))
        );

        jLabel3.setText("Logradouro");

        jLabel2.setText("Código");

        jLabel4.setText("Nome ou Razão Social");

        jLabel5.setText("Tipo Pessoa");

        jcbTipoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoPessoaActionPerformed(evt);
            }
        });

        jLabel6.setText("Sobrenome ou Nome Fantasia");

        jLabel7.setText("RG ou Inscrição Estadual");

        jLabel8.setText("Orgão Expedidor");

        jLabel9.setText("CPF Oou CPNPJ");

        jLabel10.setText("Tipo Endereço");

        jLabel11.setText("Estado");

        jLabel12.setText("Número");

        jLabel13.setText("Bairro");

        jLabel14.setText("Cidade");

        jLabel15.setText("Cep");

        jLabel16.setText("Complemento");

        jLabel17.setText("Referencia");

        javax.swing.GroupLayout jplCamposLayout = new javax.swing.GroupLayout(jplCampos);
        jplCampos.setLayout(jplCamposLayout);
        jplCamposLayout.setHorizontalGroup(
            jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplCamposLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplCamposLayout.createSequentialGroup()
                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNome)
                            .addComponent(jtfSobrenome)
                            .addGroup(jplCamposLayout.createSequentialGroup()
                                .addComponent(jtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfOrgaoExpedidor))
                            .addGroup(jplCamposLayout.createSequentialGroup()
                                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addGroup(jplCamposLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel3)
                                    .addComponent(jtfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jplCamposLayout.createSequentialGroup()
                                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jplCamposLayout.createSequentialGroup()
                                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addGap(18, 18, 18)
                                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 10, Short.MAX_VALUE)))
                        .addGap(354, 354, 354))
                    .addGroup(jplCamposLayout.createSequentialGroup()
                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplCamposLayout.createSequentialGroup()
                                .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfReferencia))
                            .addGroup(jplCamposLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplCamposLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(320, 320, 320)
                                .addComponent(jLabel11)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel17)))
                        .addContainerGap())))
        );
        jplCamposLayout.setVerticalGroup(
            jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jcbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfOrgaoExpedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplCamposLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(10, 10, 10)
                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel17)))
                .addGap(19, 19, 19))
        );

        jtConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Código Tipo Cliente", "Data Registro", "Nome ou Razão Social", "Sobrenome ou Nome Fantasia", "RG ou IE", "Orgão Expedidor", "Cpf ou Cnpj"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jplCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)))
                .addComponent(jplOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jplTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jplCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addComponent(jplOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIncluirActionPerformed
        ativarBotoes();
        jbtIncluir.setEnabled(false);
        ativarCamposDeTexto();

    }//GEN-LAST:event_jbtIncluirActionPerformed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed
        limparCampos();
        ativarCamposDeTexto();
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        checarChave();
        ControleCliente cc = new ControleCliente();
        ControleEndereco ce = new ControleEndereco();
        int chavePrimaria = cc.insert((Cliente) criarCliente());
        int chavePrimaria2 = ce.insert((Endereco) criarEndereco(chavePrimaria));
        popularChave(Integer.toString(chavePrimaria));
        desativarCamposDeTexto();

    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        new VisaoPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        int opcao = Jop.alertaOpcao("Deseja realmente excluir esse registro?");
        if (opcao == 0) {
            ControleCliente cc = new ControleCliente();
            int chavePrimaria = cc.delete((Cliente) criarCliente());
            popularChave(Integer.toString(chavePrimaria));
        }

    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarActionPerformed
        int opcao = Jop.alertaOpcao("Deseja realmente alterar esse registro?");
        if (opcao == 0) {
            ControleCliente cc = new ControleCliente();
            int chavePrimaria = cc.update((Cliente) criarCliente());
            popularChave(Integer.toString(chavePrimaria));
        }
    }//GEN-LAST:event_jbtAlterarActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        limparCampos();
        jbtIncluir.setEnabled(true);
        desativarCamposDeTexto();
        desativarBotoes();
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConsultaActionPerformed
        carregarListaClientes();
        Object[] columnNames = {"Código", "Código Tipo Cliente", "Data Resgistro", "Nome ou Razão Social","Sobrenome ou Nome Fantasia",
        "RG ou IE","Orgão Expedidor","Cpf ou Cnpj"};
        DefaultTableModel model = new DefaultTableModel(new Object[0][0], columnNames);
        for (Cliente cliente : clientes) {
            Object[] o = new Object[8];
            o[0] = cliente.getCodigo();
            o[1] = cliente.getCodigoTipoPessoa();
            o[2] = cliente.getData();
            o[3] = cliente.getNomeRazaoSocial();
            o[4] = cliente.getSobrenomeNomeFantasia();
            o[5] = cliente.getRgIe();
            o[6] = cliente.getOrgaoExpedidor();
            o[7] = cliente.getCpfCnpj();

            model.addRow(o);
        }
        jtConsulta.setModel(model);

    }//GEN-LAST:event_jbtConsultaActionPerformed

    private void jbtBuscaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscaCodigoActionPerformed
        ControleCliente cc = new ControleCliente();
        Cliente cliente = (Cliente) cc.selectCodigo(Integer.parseInt(jtfCodigo.getText()));
        ControleTipoPessoa cte = new ControleTipoPessoa();
        TipoPessoa tp = (TipoPessoa)cte.selectCodigo(cliente.getCodigoTipoPessoa());
        popularCampos(Integer.toString(cliente.getCodigo()), cliente.getCodigoTipoPessoa(), cliente.getData(), cliente.getNomeRazaoSocial(), cliente.getSobrenomeNomeFantasia(),
                cliente.getRgIe(), cliente.getOrgaoExpedidor(),cliente.getCpfCnpj());
    }//GEN-LAST:event_jbtBuscaCodigoActionPerformed

    private void jcbTipoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoPessoaActionPerformed

        private void carregarListaClientes() {
        ControleCliente cc = new ControleCliente();
        clientes = cc.select();
    }
    private void carregarListaUfs() {
        ControleUf uc = new ControleUf();
        ufs = uc.select();
        jcbEstados.removeAllItems();
        for (Uf uf : ufs) {
            jcbEstados.addItem(uf);
        }
    }

    private void carregarListaTipoEnderecos() {
        ControleTipoEndereco ctp = new ControleTipoEndereco();
        tipoEnderecos = ctp.select();
        jcbTipoEndereco.removeAllItems();
        for (TipoEndereco tEndereco : tipoEnderecos) {
            jcbTipoEndereco.addItem(tEndereco);
        }
    }

    private void carregarListaTipoPessoas() {
        ControleTipoPessoa ctp = new ControleTipoPessoa();
        tipoPessoas = ctp.select();
        jcbTipoPessoa.removeAllItems();
        for (TipoPessoa tpessoa : tipoPessoas) {
            jcbTipoPessoa.addItem(tpessoa);
        }

    }

    private void checarChave() {
        if (jtfCodigo.getText().length() <= 0) {
            jtfCodigo.setText("0");
        }
    }

    private Object criarCliente() {

        int codigoCliente = Integer.parseInt(jtfCodigo.getText());

        TipoPessoa tpessoa = (TipoPessoa) jcbTipoPessoa.getSelectedItem();
        int codigo_TipoPessoa = tpessoa.getCodigo();

        Date dataRegisto = new Date();
        String nome = jtfNome.getText();
        String sbNome = jtfSobrenome.getText();
        String rgIe = jtfRg.getText();
        String ogExp = jtfOrgaoExpedidor.getText();
        String cpfCnpj = jtfCpf.getText();

        Cliente cliente = new Cliente(codigoCliente, codigo_TipoPessoa, dataRegisto, nome, sbNome, rgIe, ogExp, cpfCnpj);
        return cliente;
    }
    
        private Object criarEndereco(int chaveStrangeira) {
        
        int codigoCliente = chaveStrangeira;

        TipoEndereco tendereco = (TipoEndereco) jcbTipoEndereco.getSelectedItem();
        int codigo_TipoEndereco = tendereco.getCodigo();
        
        Uf uf = (Uf) jcbEstados.getSelectedItem();
        int codigo_uf = uf.getCodigo();
                

        String logradouro = jtfLogradouro.getText();
        String numero = jtfNumero.getText();
        String complemento = jtfComplemento.getText();
        String bairro = jtfBairro.getText();
        String cidade = jtfCidade.getText();
        String cep = jtfCep.getText();
        String referencia = jtfReferencia.getText();

        Endereco endereco = new Endereco(0,codigoCliente, codigo_TipoEndereco, codigo_uf, logradouro, numero, complemento, bairro, cidade,cep,referencia);
        return endereco;
    }

    private void desativarBotoes() {
        jbtNovo.setEnabled(false);
        jbtSalvar.setEnabled(false);
        jbtAlterar.setEnabled(false);
        jbtCancelar.setEnabled(false);
        jbtExcluir.setEnabled(false);
    }

    private void ativarBotoes() {
        jbtIncluir.setEnabled(true);
        jbtNovo.setEnabled(true);
        jbtSalvar.setEnabled(true);
        jbtAlterar.setEnabled(true);
        jbtCancelar.setEnabled(true);
        jbtExcluir.setEnabled(true);
    }

    private void desativarCamposDeTexto() {
        jtfCodigo.setEnabled(false);
        jtfLogradouro.setEnabled(false);
    }

    private void ativarCamposDeTexto() {
        jtfCodigo.setEnabled(true);
        jtfLogradouro.setEnabled(true);
    }

    private void limparCampos() {
        jtfCodigo.setText(null);
        jtfLogradouro.setText(null);
    }

    private void popularChave(String chave) {
        jtfCodigo.setText(chave);

    }

    private void popularCampos(String codigo, int codigoTipoPessoa, Date registro, String nome, String sobrenome, String rg, String orgao, String cpf) {
        jtfCodigo.setText(codigo);
        jtfNome.setText(nome);
        jtfSobrenome.setText(sobrenome);
        jtfRg.setText(rg);
        jtfOrgaoExpedidor.setText(orgao);
        jtfCpf.setText(cpf);

        int index = 0;
        for (int i = 0; i < tipoPessoas.size(); i++) {
            if (tipoPessoas.get(i).getCodigo() == codigoTipoPessoa) { // Or use equals() if it actually returns an Object.
                index = i;
            }
        }

        jcbTipoPessoa.setSelectedIndex(index);
        

    }
    
    private void popularEndereco()
    {
        /*int codigoCliente = chaveStrangeira;

        TipoEndereco tendereco = (TipoEndereco) jcbTipoEndereco.getSelectedItem();
        int codigo_TipoEndereco = tendereco.getCodigo();
        
        Uf uf = (Uf) jcbEstados.getSelectedItem();
        int codigo_uf = uf.getCodigo();
                

        String logradouro = jtfLogradouro.getText();
        String numero = jtfNumero.getText();
        String complemento = jtfComplemento.getText();
        String bairro = jtfBairro.getText();
        String cidade = jtfCidade.getText();
        String cep = jtfCep.getText();
        String referencia = jtfReferencia.getText();
    */
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jbtAlterar;
    private javax.swing.JButton jbtBuscaCodigo;
    private javax.swing.JToggleButton jbtCancelar;
    private javax.swing.JButton jbtConsulta;
    private javax.swing.JToggleButton jbtExcluir;
    private javax.swing.JButton jbtIncluir;
    private javax.swing.JToggleButton jbtNovo;
    private javax.swing.JToggleButton jbtSair;
    private javax.swing.JToggleButton jbtSalvar;
    private javax.swing.JComboBox jcbEstados;
    private javax.swing.JComboBox jcbTipoEndereco;
    private javax.swing.JComboBox jcbTipoPessoa;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JPanel jplCampos;
    private javax.swing.JPanel jplOpcoes;
    private javax.swing.JPanel jplTitulo;
    private javax.swing.JTable jtConsulta;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCep;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfLogradouro;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfOrgaoExpedidor;
    private javax.swing.JTextField jtfReferencia;
    private javax.swing.JTextField jtfRg;
    private javax.swing.JTextField jtfSobrenome;
    // End of variables declaration//GEN-END:variables
}
