/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import fanapUtil.Jop;
import controle.ControleCliente;
import controle.ControleEndereco;
import controle.ControleTipoEndereco;
import controle.ControleTipoPessoa;
import controle.ControleUf;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Endereco;
import modelo.TipoEndereco;
import modelo.TipoPessoa;
import modelo.Uf;

/**
 *
 * @author T-Gamer
 */
public class VisaoEndereco extends javax.swing.JFrame {

    private List<TipoPessoa> tipoPessoas;
    private List<TipoEndereco> tipoEnderecos;
    private List<Uf> ufs;
    private List<Cliente> clientes;
    private List<Endereco> enderecos;

    /**
     * Creates new form PaisVisao
     */
    public VisaoEndereco() {

        initComponents();
        desativarBotoes();
        desativarCamposDeTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jplCampos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfLogradouro = new javax.swing.JTextField();
        jtfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbCliente = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jtfSobrenome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfRgIe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfOrgaoExpedidor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcbTipoEndereco = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jcbEstados = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jtfCidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtfCep = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfComplemento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfReferencia = new javax.swing.JTextField();
        jbtBuscaCodigo = new javax.swing.JButton();
        jbtIncluir = new javax.swing.JButton();
        jbtNovo = new javax.swing.JToggleButton();
        jbtSalvar = new javax.swing.JToggleButton();
        jbtAlterar = new javax.swing.JToggleButton();
        jbtCancelar = new javax.swing.JToggleButton();
        jbtExcluir = new javax.swing.JToggleButton();
        jbtConsulta = new javax.swing.JButton();
        jcbConsulta = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jbtSair = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsulta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jplTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Manter Endereco");

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_pequeno.png"))); // NOI18N

        javax.swing.GroupLayout jplTituloLayout = new javax.swing.GroupLayout(jplTitulo);
        jplTitulo.setLayout(jplTituloLayout);
        jplTituloLayout.setHorizontalGroup(
            jplTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplTituloLayout.createSequentialGroup()
                .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplTituloLayout.setVerticalGroup(
            jplTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplTituloLayout.createSequentialGroup()
                .addGroup(jplTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlLogo)
                    .addGroup(jplTituloLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jplCampos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Logradouro");

        jLabel2.setText("Código");

        jLabel4.setText("Nome ou Razão Social");

        jLabel5.setText("Cliente");

        jcbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Sobrenome ou Nome Fantasia");

        jLabel7.setText("RG ou Inscrição Estadual");

        jLabel8.setText("Orgão Expedidor");

        jLabel9.setText("CPF Oou CPNPJ");

        jLabel10.setText("Tipo Endereço");

        jLabel11.setText("Estado");

        jLabel12.setText("Número");

        jLabel13.setText("Bairro");

        jLabel14.setText("Cidade");

        jLabel15.setText("Cep");

        jLabel16.setText("Complemento");

        jLabel17.setText("Referencia");

        jbtBuscaCodigo.setText("Busca por Código");
        jbtBuscaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscaCodigoActionPerformed(evt);
            }
        });

        jbtIncluir.setText("Editar");
        jbtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIncluirActionPerformed(evt);
            }
        });

        jbtNovo.setText("Novo");
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtAlterar.setText("Alterar");
        jbtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarActionPerformed(evt);
            }
        });

        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jbtExcluir.setText("Excluir");
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtConsulta.setText("Consultar");
        jbtConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConsultaActionPerformed(evt);
            }
        });

        jcbConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Residencial", "Comercial", "Correspêndcia", "Entrega", "Recado", "Outros(s)", "Cliente/Cep" }));

        jLabel18.setText("Consultar Endereços:");

        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplCamposLayout = new javax.swing.GroupLayout(jplCampos);
        jplCampos.setLayout(jplCamposLayout);
        jplCamposLayout.setHorizontalGroup(
            jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplCamposLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jplCamposLayout.createSequentialGroup()
                            .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jcbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jplCamposLayout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(320, 320, 320)
                            .addComponent(jLabel11))
                        .addGroup(jplCamposLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtBuscaCodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jtfNome)
                        .addGroup(jplCamposLayout.createSequentialGroup()
                            .addComponent(jtfRgIe, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfOrgaoExpedidor))
                        .addComponent(jtfSobrenome)
                        .addComponent(jLabel17)
                        .addComponent(jtfReferencia))
                    .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addGroup(jplCamposLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(73, 73, 73)
                            .addComponent(jLabel8))
                        .addComponent(jLabel3)
                        .addComponent(jtfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jplCamposLayout.createSequentialGroup()
                            .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jplCamposLayout.createSequentialGroup()
                            .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addGap(18, 18, 18)
                            .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jtfCep)))))
                .addGap(18, 18, 18)
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplCamposLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplCamposLayout.createSequentialGroup()
                                    .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jbtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jplCamposLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jbtNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbtSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbtAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbtCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbtExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(7, 7, 7))
                                .addComponent(jcbConsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jplCamposLayout.createSequentialGroup()
                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jplCamposLayout.setVerticalGroup(
            jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBuscaCodigo)
                    .addComponent(jcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jbtIncluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplCamposLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtfOrgaoExpedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtExcluir))
                            .addComponent(jtfRgIe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplCamposLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtSair))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jplCamposLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addGap(9, 9, 9)
                                .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jcbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jplCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtConsulta))
                        .addGap(15, 15, 15))
                    .addGroup(jplCamposLayout.createSequentialGroup()
                        .addComponent(jbtNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jtConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Código Tipo Cliente", "Data Registro", "Nome ou Razão Social", "Sobrenome ou Nome Fantasia", "RG ou IE", "Orgão Expedidor", "Cpf ou Cnpj"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jplCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jplTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jplCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbClienteActionPerformed

    private void jbtBuscaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscaCodigoActionPerformed

        //ControleCliente cc = new ControleCliente();
        // Cliente cliente = (Cliente) cc.selectCodigo(Integer.parseInt(jtfCodigo.getText()));
       // popularCampos(Integer.toString(cliente.getCodigo()), cliente.getCodigoTipoPessoa(), cliente.getData(), cliente.getNomeRazaoSocial(), cliente.getSobrenomeNomeFantasia(),
        //cliente.getRgIe(), cliente.getOrgaoExpedidor(), cliente.getCpfCnpj());
        // Cliente cliente = (Cliente) jcbCliente.getSelectedItem();
        ControleEndereco ce = new ControleEndereco();

        Endereco endereco = (Endereco) ce.selectCodigo(Integer.parseInt(jtfCodigo.getText()));
        popularEndereco(endereco.getCodigo(), endereco.getCodigoCliente(), endereco.getCodigoTipoEndereco(), endereco.getCodigoUf(), endereco.getLogradouro(), endereco.getBairro(),
                endereco.getCep(), endereco.getCidade(), endereco.getComplemento(), endereco.getNumero(), endereco.getReferencia());
    }//GEN-LAST:event_jbtBuscaCodigoActionPerformed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        new VisaoPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jbtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConsultaActionPerformed

        String opcao = (String) jcbConsulta.getSelectedItem();
        switch (opcao) {
            case "Todos":
                todosOsEnderecos();
                break;
            case "Residencial":
                tipoEndereco(1);
                break;
            case "Comercial":
                tipoEndereco(2);
                break;
            case "Correspêndcia":
                tipoEndereco(3);
                break;
            case "Entrega":
                tipoEndereco(4);
                break;
            case "Recado":
                tipoEndereco(5);
                break;
            case "Outros(s)":
                tipoEndereco(6);
                break;
            case "Cliente/Cep":
                enderecoPorCodigoClienteCep();
                break;
            default:

        }
    }//GEN-LAST:event_jbtConsultaActionPerformed


    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        limparCampos();
        limparListas();
        jbtIncluir.setEnabled(true);
        desativarCamposDeTexto();
        desativarBotoes();
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarActionPerformed
        int opcao = Jop.alertaOpcao("Deseja realmente alterar esse registro?");
        if (opcao == 0) {
            int index = jcbCliente.getSelectedIndex();
            int codigoCliente = clientes.get(index).getCodigo();

            ControleEndereco ce = new ControleEndereco();
            Endereco enderecoVelho = (Endereco) ce.selectCodigoCliente(codigoCliente, jtfCep.getText());
            Endereco enderecoNovo = (Endereco) atualizarEndereco(codigoCliente, enderecoVelho.getCodigo());
            int chave = ce.update(enderecoNovo);
            popularChave(Integer.toString(chave));
        }


    }//GEN-LAST:event_jbtAlterarActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        int opcao = Jop.alertaOpcao("Deseja realmente excluir esse registro?");
        if (opcao == 0) {
            ControleCliente cc = new ControleCliente();
            int chavePrimaria = cc.delete((Cliente) criarCliente());
            popularChave(Integer.toString(chavePrimaria));
        }
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        checarChave();
        ControleCliente cc = new ControleCliente();
        ControleEndereco ce = new ControleEndereco();
        int chavePrimaria = cc.insert((Cliente) criarCliente());
        ce.insert((Endereco) criarEndereco(chavePrimaria));
        popularChave(Integer.toString(chavePrimaria));
        desativarCamposDeTexto();
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed
        limparCampos();
        ativarCamposDeTexto();
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIncluirActionPerformed
        ativarBotoes();
        jbtIncluir.setEnabled(false);
        carregarListaUfs();
        carregarListaTipoEnderecos();
        carregarListaTipoPessoas();
        carregarListaClientes();
        ativarCamposDeTexto();

    }//GEN-LAST:event_jbtIncluirActionPerformed

    private void carregarListaClientes() {
        ControleCliente cc = new ControleCliente();
        clientes = cc.select();
    }

    private void carregarListaEnderecos() {
        ControleEndereco ce = new ControleEndereco();
        enderecos = ce.select();
    }

    private void carregarListaUfs() {
        ControleUf uc = new ControleUf();
        ufs = uc.select();
        jcbEstados.removeAllItems();
        for (Uf uf : ufs) {
            jcbEstados.addItem(uf);
        }
    }

    private void carregarListaTipoEnderecos() {
        ControleTipoEndereco ctp = new ControleTipoEndereco();
        tipoEnderecos = ctp.select();
        jcbTipoEndereco.removeAllItems();
        for (TipoEndereco tEndereco : tipoEnderecos) {
            jcbTipoEndereco.addItem(tEndereco);
        }
    }

    private void carregarListaTipoPessoas() {
        ControleCliente cc = new ControleCliente();
        clientes = cc.select();
        jcbCliente.removeAllItems();
        for (Cliente c : clientes) {
            jcbCliente.addItem(c);
        }

    }

    private void limparListas() {
        clientes.clear();
        ufs.clear();
        tipoEnderecos.clear();
        tipoPessoas.clear();
        jcbEstados.removeAllItems();
        jcbTipoEndereco.removeAllItems();
        jcbCliente.removeAllItems();

    }

    private void checarChave() {
        if (jtfCodigo.getText().length() <= 0) {
            jtfCodigo.setText("0");
        }
    }

    private Object criarCliente() {

        int codigoCliente = Integer.parseInt(jtfCodigo.getText());

        TipoPessoa tpessoa = (TipoPessoa) jcbCliente.getSelectedItem();
        int codigo_TipoPessoa = tpessoa.getCodigo();

        Date dataRegisto = new Date();
        String nome = jtfNome.getText();
        String sbNome = jtfSobrenome.getText();
        String rgIe = jtfRgIe.getText();
        String ogExp = jtfOrgaoExpedidor.getText();
        String cpfCnpj = jtfCpf.getText();

        Cliente cliente = new Cliente(codigoCliente, codigo_TipoPessoa, dataRegisto, nome, sbNome, rgIe, ogExp, cpfCnpj);
        return cliente;
    }

    private Endereco criarEndereco(int chaveStrangeira) {

        int codigoCliente = chaveStrangeira;

        TipoEndereco tendereco = (TipoEndereco) jcbTipoEndereco.getSelectedItem();
        int codigo_TipoEndereco = tendereco.getCodigo();

        Uf uf = (Uf) jcbEstados.getSelectedItem();
        int codigo_uf = uf.getCodigo();

        String logradouro = jtfLogradouro.getText();
        String numero = jtfNumero.getText();
        String complemento = jtfComplemento.getText();
        String bairro = jtfBairro.getText();
        String cidade = jtfCidade.getText();
        String cep = jtfCep.getText();
        String referencia = jtfReferencia.getText();

        Endereco endereco = new Endereco(0, codigoCliente, codigo_TipoEndereco, codigo_uf, logradouro, numero, complemento, bairro, cidade, cep, referencia);
        return endereco;
    }

    private Endereco atualizarEndereco(int chaveStrangeira, int pk) {

        int codigoCliente = chaveStrangeira;

        TipoEndereco tendereco = (TipoEndereco) jcbTipoEndereco.getSelectedItem();
        int codigo_TipoEndereco = tendereco.getCodigo();

        Uf uf = (Uf) jcbEstados.getSelectedItem();
        int codigo_uf = uf.getCodigo();

        String logradouro = jtfLogradouro.getText();
        String numero = jtfNumero.getText();
        String complemento = jtfComplemento.getText();
        String bairro = jtfBairro.getText();
        String cidade = jtfCidade.getText();
        String cep = jtfCep.getText();
        String referencia = jtfReferencia.getText();

        Endereco endereco = new Endereco(pk, codigoCliente, codigo_TipoEndereco, codigo_uf, logradouro, numero, complemento, bairro, cidade, cep, referencia);
        return endereco;
    }

    private void desativarBotoes() {
        jbtNovo.setEnabled(false);
        jbtSalvar.setEnabled(false);
        jbtAlterar.setEnabled(false);
        jbtCancelar.setEnabled(false);
        jbtExcluir.setEnabled(false);
        jcbEstados.setEnabled(false);
        jcbTipoEndereco.setEnabled(false);
        jcbCliente.setEnabled(false);
    }

    private void ativarBotoes() {
        jbtIncluir.setEnabled(true);
        jbtNovo.setEnabled(true);
        jbtSalvar.setEnabled(true);
        jbtAlterar.setEnabled(true);
        jbtCancelar.setEnabled(true);
        jbtExcluir.setEnabled(true);
        jcbEstados.setEnabled(true);
        jcbTipoEndereco.setEnabled(true);
        jcbCliente.setEnabled(true);
    }

    private void desativarCamposDeTexto() {
        jtfCodigo.setEnabled(false);
        jtfNome.setEnabled(false);
        jtfLogradouro.setEnabled(false);
        jtfBairro.setEnabled(false);
        jtfCep.setEnabled(false);
        jtfCidade.setEnabled(false);
        jtfComplemento.setEnabled(false);
        jtfCpf.setEnabled(false);
        jtfNumero.setEnabled(false);
        jtfOrgaoExpedidor.setEnabled(false);
        jtfReferencia.setEnabled(false);
        jtfRgIe.setEnabled(false);
        jtfSobrenome.setEnabled(false);

    }

    private void ativarCamposDeTexto() {
        jtfCodigo.setEnabled(true);
        jtfNome.setEnabled(true);
        jtfLogradouro.setEnabled(true);
        jtfBairro.setEnabled(true);
        jtfCep.setEnabled(true);
        jtfCidade.setEnabled(true);
        jtfComplemento.setEnabled(true);
        jtfCpf.setEnabled(true);
        jtfNumero.setEnabled(true);
        jtfOrgaoExpedidor.setEnabled(true);
        jtfReferencia.setEnabled(true);
        jtfRgIe.setEnabled(true);
        jtfSobrenome.setEnabled(true);
    }

    private void limparCampos() {
        jtfCodigo.setText(null);
        jtfLogradouro.setText(null);
    }

    private void popularChave(String chave) {
        jtfCodigo.setText(chave);

    }

    private void popularCampos(String codigo, int codigoTipoPessoa, Date registro, String nome, String sobrenome, String rg, String orgao, String cpf) {
        jtfCodigo.setText(codigo);
        jtfNome.setText(nome);
        jtfSobrenome.setText(sobrenome);
        jtfRgIe.setText(rg);
        jtfOrgaoExpedidor.setText(orgao);
        jtfCpf.setText(cpf);

        int index = 0;
        for (int i = 0; i < tipoPessoas.size(); i++) {
            if (tipoPessoas.get(i).getCodigo() == codigoTipoPessoa) { // Or use equals() if it actually returns an Object.
                index = i;
            }
        }

        jcbCliente.setSelectedIndex(index);

    }

    private void popularEndereco(int codigo, int codigoCliente, int codigoTipoEndereco, int codigoEstado, String logradouro, String bairro, String cep, String cidade, String complemento, String numero, String referencia) {
        jtfCodigo.setText(Integer.toString(codigo));
        jtfLogradouro.setText(logradouro);
        jtfBairro.setText(bairro);
        jtfCep.setText(cep);
        jtfCidade.setText(cidade);
        jtfComplemento.setText(complemento);
        jtfNumero.setText(numero);
        jtfReferencia.setText(referencia);

        int index = 0;
        for (int i = 0; i < tipoEnderecos.size(); i++) {
            if (tipoEnderecos.get(i).getCodigo() == codigoTipoEndereco) { // Or use equals() if it actually returns an Object.
                index = i;
                break;
            }
        }

        jcbTipoEndereco.setSelectedIndex(index);

        index = 0;
        for (int i = 0; i < ufs.size(); i++) {
            if (ufs.get(i).getCodigo() == codigoEstado) { // Or use equals() if it actually returns an Object.
                index = i;
                break;
            }
        }

        jcbEstados.setSelectedIndex(index);

        index = 0;
        for (int i = 0; i < clientes.size(); i++) {
            if (clientes.get(i).getCodigo() == codigoCliente) { // Or use equals() if it actually returns an Object.
                index = i;
            }
        }

        jcbCliente.setSelectedIndex(index);
    }

    private void todosOsEnderecos() {
        carregarListaEnderecos();
        Object[] columnNames = {"Código Endereco", "Código Cliente", "Código Tipo Endereço", "Código UF", "Logradouro",
            "Número", "Complemento", "Bairro", "Cidade", "Cep", "Referência"};
        DefaultTableModel model = new DefaultTableModel(new Object[0][0], columnNames);
        for (Endereco endereco : enderecos) {
            Object[] o = new Object[11];
            o[0] = endereco.getCodigo();
            o[1] = endereco.getCodigoCliente();
            o[2] = endereco.getCodigoTipoEndereco();
            o[3] = endereco.getCodigoUf();
            o[4] = endereco.getLogradouro();
            o[5] = endereco.getNumero();
            o[6] = endereco.getComplemento();
            o[7] = endereco.getBairro();
            o[8] = endereco.getCidade();
            o[9] = endereco.getCep();
            o[10] = endereco.getReferencia();

            model.addRow(o);
        }
        jtConsulta.setModel(model);

    }

    private void tipoEndereco(int chaveEstrangeira) {
        ControleEndereco ce = new ControleEndereco();
        enderecos = ce.selectTipoEndereco(chaveEstrangeira);
        Object[] columnNames = {"Código Endereco", "Código Cliente", "Código Tipo Endereço", "Código UF", "Logradouro",
            "Número", "Complemento", "Bairro", "Cidade", "Cep", "Referência"};
        DefaultTableModel model = new DefaultTableModel(new Object[0][0], columnNames);
        for (Endereco endereco : enderecos) {
            Object[] o = new Object[11];
            o[0] = endereco.getCodigo();
            o[1] = endereco.getCodigoCliente();
            o[2] = endereco.getCodigoTipoEndereco();
            o[3] = endereco.getCodigoUf();
            o[4] = endereco.getLogradouro();
            o[5] = endereco.getNumero();
            o[6] = endereco.getComplemento();
            o[7] = endereco.getBairro();
            o[8] = endereco.getCidade();
            o[9] = endereco.getCep();
            o[10] = endereco.getReferencia();

            model.addRow(o);
        }
        jtConsulta.setModel(model);

    }

    private void enderecoPorCodigoClienteCep() {
        int index = jcbCliente.getSelectedIndex();
        int codigoCliente = clientes.get(index).getCodigo();
        ControleEndereco ce = new ControleEndereco();
        Endereco endereco = (Endereco) ce.selectCodigoCliente(codigoCliente, jtfCep.getText());
        Object[] columnNames = {"Código Endereco", "Código Cliente", "Código Tipo Endereço", "Código UF", "Logradouro",
            "Número", "Complemento", "Bairro", "Cidade", "Cep", "Referência"};
        DefaultTableModel model = new DefaultTableModel(new Object[0][0], columnNames);
        Object[] o = new Object[11];
        o[0] = endereco.getCodigo();
        o[1] = endereco.getCodigoCliente();
        o[2] = endereco.getCodigoTipoEndereco();
        o[3] = endereco.getCodigoUf();
        o[4] = endereco.getLogradouro();
        o[5] = endereco.getNumero();
        o[6] = endereco.getComplemento();
        o[7] = endereco.getBairro();
        o[8] = endereco.getCidade();
        o[9] = endereco.getCep();
        o[10] = endereco.getReferencia();

        model.addRow(o);

        jtConsulta.setModel(model);

    }

    private void clientePorRgIe() {
        ControleCliente cc = new ControleCliente();
        Cliente cliente = (Cliente) cc.selectRgIe(jtfRgIe.getText());
        Object[] columnNames = {"Código", "Código Tipo Cliente", "Data Resgistro", "Nome ou Razão Social", "Sobrenome ou Nome Fantasia",
            "RG ou IE", "Orgão Expedidor", "Cpf ou Cnpj"};
        DefaultTableModel model = new DefaultTableModel(new Object[0][0], columnNames);
        Object[] o = new Object[8];
        o[0] = cliente.getCodigo();
        o[1] = cliente.getCodigoTipoPessoa();
        o[2] = cliente.getData();
        o[3] = cliente.getNomeRazaoSocial();
        o[4] = cliente.getSobrenomeNomeFantasia();
        o[5] = cliente.getRgIe();
        o[6] = cliente.getOrgaoExpedidor();
        o[7] = cliente.getCpfCnpj();

        model.addRow(o);

        jtConsulta.setModel(model);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaoEndereco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jbtAlterar;
    private javax.swing.JButton jbtBuscaCodigo;
    private javax.swing.JToggleButton jbtCancelar;
    private javax.swing.JButton jbtConsulta;
    private javax.swing.JToggleButton jbtExcluir;
    private javax.swing.JButton jbtIncluir;
    private javax.swing.JToggleButton jbtNovo;
    private javax.swing.JToggleButton jbtSair;
    private javax.swing.JToggleButton jbtSalvar;
    private javax.swing.JComboBox jcbCliente;
    private javax.swing.JComboBox jcbConsulta;
    private javax.swing.JComboBox jcbEstados;
    private javax.swing.JComboBox jcbTipoEndereco;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JPanel jplCampos;
    private javax.swing.JPanel jplTitulo;
    private javax.swing.JTable jtConsulta;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCep;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfLogradouro;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfOrgaoExpedidor;
    private javax.swing.JTextField jtfReferencia;
    private javax.swing.JTextField jtfRgIe;
    private javax.swing.JTextField jtfSobrenome;
    // End of variables declaration//GEN-END:variables
}
